version: '3.8'

services:

  db:
    image: postgres:14.0-alpine
    volumes:
      - ./db:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env

  web:
      build: web
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./web:/src/web
      ports:
        - "8000:8000"
      env_file:
        - ./.env
      depends_on:
        - db